apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - portfolioservice-configmap.yaml
  - portfolioservice-postgres.yaml
  - portfolioservice-deployment.yaml
  - portfolioservice-service.yaml

labels:
  - pairs:
      part-of: crypto-tracker
