apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-config.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

labels:
  - pairs:
      part-of: crypto-tracker
