apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - userservice-configmap.yaml
  - userservice-postgres.yaml
  - userservice-deployment.yaml
  - userservice-service.yaml

labels:
  - pairs:
      part-of: crypto-tracker
