apiVersion: v1
kind: ConfigMap
metadata:
  name: alertservice-config
data:
  FLASK_ENV: "production"
  FRONTEND_URL: "http://localhost:3000"
  PRICING_SERVICE_URL: "http://pricing-service:12000"
  DB_HOST: "alert-service-db"
  DB_PORT: "5432"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "alert_user"
  POSTGRES_DB: "crypto_alerts"
  PORT: "5000"

