apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertservice-configmap.yaml
  - alertservice-postgres.yaml
  - alertservice-deployment.yaml
  - alertservice-service.yaml

labels:
  - pairs:
      part-of: crypto-tracker
