apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pricingservice-configmap.yaml
  - pricingservice-postgres.yaml
  - pricingservice-jobs.yaml
  - pricingservice-deployment.yaml
  - pricingservice-service.yaml

labels:
  - pairs:
      part-of: crypto-tracker
