apiVersion: v1
kind: ConfigMap
metadata:
  name: pricing-service-config
  labels:
    app: pricing-service
data:
  POSTGRES_DB: pricing_db
  DB_HOST: pricing-service-db
  DB_PORT: "5432"
  SERVICE_NAME: pricing-service
  SERVICE_VERSION: "1.0.0"
  ENVIRONMENT: development
  EXTERNAL_LOG_LEVEL: WARNING
  LOG_REQUEST_COMPLETION: errors
  ALERT_SERVICE_URL: http://alert-service:5000
